// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	logging "github.com/apetsko/gophermart/internal/logging"

	mock "github.com/stretchr/testify/mock"

	models "github.com/apetsko/gophermart/internal/models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AddOrder provides a mock function with given fields: ctx, userID, order
func (_m *Storage) AddOrder(ctx context.Context, userID int64, order string) error {
	ret := _m.Called(ctx, userID, order)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUser provides a mock function with given fields: ctx, u
func (_m *Storage) AddUser(ctx context.Context, u *models.UserEntry) (int, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserEntry) (int, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserEntry) int); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserEntry) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Balance provides a mock function with given fields: ctx, id
func (_m *Storage) Balance(ctx context.Context, id int64) (*models.UserBalance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 *models.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.UserBalance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.UserBalance); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, login
func (_m *Storage) GetUser(ctx context.Context, login string) (*models.UserEntry, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.UserEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.UserEntry, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserEntry); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrders provides a mock function with given fields: ctx, id
func (_m *Storage) ListOrders(ctx context.Context, id int64) ([]models.UserOrderEntry, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListOrders")
	}

	var r0 []models.UserOrderEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.UserOrderEntry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.UserOrderEntry); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserOrderEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, id, wd, logger
func (_m *Storage) Withdraw(ctx context.Context, id int64, wd models.Withdraw, logger logging.Logger) (*models.UserBalance, error) {
	ret := _m.Called(ctx, id, wd, logger)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *models.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.Withdraw, logging.Logger) (*models.UserBalance, error)); ok {
		return rf(ctx, id, wd, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.Withdraw, logging.Logger) *models.UserBalance); ok {
		r0 = rf(ctx, id, wd, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.Withdraw, logging.Logger) error); ok {
		r1 = rf(ctx, id, wd, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdrawals provides a mock function with given fields: ctx, id
func (_m *Storage) Withdrawals(ctx context.Context, id int64) ([]models.Withdraw, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Withdrawals")
	}

	var r0 []models.Withdraw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.Withdraw, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.Withdraw); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Withdraw)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
