FROM golang:1.22 as builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -o gophermart ./cmd/gophermart
FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/gophermart /app/gophermart
CMD ["/app/gophermart"]
